# Shared Gradle configuration
org.gradle.jvmargs=-Xmx4G -Duser.language=en -Duser.country=US -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# IntelliJ IDEA is not yet fully compatible with configuration cache with Fabric Loom.
org.gradle.configuration-cache=false

org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
dev.kikugie.stonecutter.hard_mode=true

# Shared project properties
minecraft_version=26.1.2
mod_version=0.5.0
maven_group=top.katton
archives_base_name=katton

# Fabric
loader_version=0.19.5
loom_version=1.18-SNAPSHOT
fabric_api_version=0.144.0+26.1

# NeoForge
minecraft_version_range=[26.1, 26.1.2]
neo_version=26.1.2.30-beta
mod_id=katton
mod_name=Katton
mod_license=MIT

# Paper
paper_api_version=26.1.2.build.+
